version: '3.3'

services:

  wordpress:
    container_name: wordpress
    image: wordpress
    restart: always
    ports:
      - 9000:80
    environment:
      WORDPRESS_DB_HOST: db-wordpress
      WORDPRESS_DB_USER: wordpress-user
      WORDPRESS_DB_PASSWORD: wordpress-password
      WORDPRESS_DB_NAME: wordpress-db
      WORDPRESS_DB_PORT: '3307'
    volumes:
      - /home/vagrant/dockerfiles/wordpress:/var/www/html

  db-wordpress:
    container_name: db-wordpress
    image: mysql:5.7
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: wordpress-db
      MYSQL_USER: wordpress-user
      MYSQL_PASSWORD: wordpress-password
      MYSQL_RANDOM_ROOT_PASSWORD: '1'
volumes:
  wordpress:
